version: "3.9"

services:
  dominatus-be:
    container_name: dominatus-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9000:8443"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Xmx128m -Xms64m -XX:+UseSerialGC
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: unless-stopped
    networks:
      - praetor-net

networks:
  praetor-net:
    driver: bridge
